"""
System 5 Term Mapping

This module maps the 20 System 5 terms (hyperedges) from Dan's analysis
to the 20 rooted forest configurations generated by our algorithm.

The mapping connects:
- Bracket notation (parentheses) to rooted forest structure
- Term names and descriptions to structural properties
- Triadic organization (Cerebral, Autonomic, Somatic) to virtual image patterns

References:
- Dan's System 5 Explorations v7
- Schwarz Cycle Detail DDD
- Campbell, R. (1985). Fisherman's Guide
"""

from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
from enum import Enum

from .rooted_forests import (
    RootedForest, RootedForestGenerator, 
    get_system5_configurations, analyze_forest
)


# =============================================================================
# TERM DEFINITIONS FROM DAN'S ANALYSIS
# =============================================================================

class Triad(Enum):
    """The three triads of System 5."""
    CEREBRAL = "Cerebral"      # Neocortex - conscious processing
    AUTONOMIC = "Autonomic"    # Limbic - emotive balance
    SOMATIC = "Somatic"        # Basal - physical response


class Polarity(Enum):
    """Universal (U) or Particular (P) polarity."""
    UNIVERSAL = "U"
    PARTICULAR = "P"


@dataclass
class System5Term:
    """A System 5 term (hyperedge) with its properties."""
    number: int                    # T01-T20
    name: str                      # Descriptive name
    bracket_notation: str          # Parenthesis structure
    description: str               # Functional description
    polarity: Polarity             # U or P
    triad: Optional[Triad]         # Primary triad association
    brain_region: Optional[str]    # Neural correlate
    business_function: Optional[str]  # Organizational correlate


# The 20 terms from Dan's System 5 Explorations
SYSTEM5_TERMS = [
    System5Term(
        number=1,
        name="Universal Cognitive Hierarchy",
        bracket_notation="((((())))))",
        description="Foundational cognitive structure from Host Idea to Behavioral Form",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Neocortex (integrated)",
        business_function="Strategic Planning"
    ),
    System5Term(
        number=2,
        name="Sympathetic Ideation Dynamics",
        bracket_notation="(())()()())",
        description="Dynamic formation and evolution of ideas influenced by emotional states",
        polarity=Polarity.PARTICULAR,
        triad=Triad.AUTONOMIC,
        brain_region="Sympathetic nervous system",
        business_function="Innovation/R&D"
    ),
    System5Term(
        number=3,
        name="Emotional Knowledge Exchange",
        bracket_notation="(())(())()",
        description="Transfer and exchange of emotional knowledge",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.AUTONOMIC,
        brain_region="Limbic system",
        business_function="Marketing (Emotional Feedback)"
    ),
    System5Term(
        number=4,
        name="Parasympathetic Action Restraint",
        bracket_notation="(()())()())",
        description="Moderation and control of actions by parasympathetic system",
        polarity=Polarity.PARTICULAR,
        triad=Triad.AUTONOMIC,
        brain_region="Parasympathetic nervous system",
        business_function="Risk Management"
    ),
    System5Term(
        number=5,
        name="Goal-Oriented Interaction Flow",
        bracket_notation="(()())(())",
        description="Interactive flow of goal-oriented processes",
        polarity=Polarity.PARTICULAR,
        triad=Triad.CEREBRAL,
        brain_region="Prefrontal cortex",
        business_function="Project Management"
    ),
    System5Term(
        number=6,
        name="Somatic Response Initiation",
        bracket_notation="((()))()())",
        description="Initiation of physical responses connecting internal states to external actions",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.SOMATIC,
        brain_region="Motor cortex",
        business_function="Operations"
    ),
    System5Term(
        number=7,
        name="Discretionary Process Integration",
        bracket_notation="((()))(())",
        description="Integration of discretionary processes informed by cognitive and emotional factors",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Executive function",
        business_function="Decision Making"
    ),
    System5Term(
        number=8,
        name="Corporeal Autonomy Framework",
        bracket_notation="(()()())()",
        description="Framework of corporeal autonomy orchestrating body's independent functions",
        polarity=Polarity.PARTICULAR,
        triad=Triad.SOMATIC,
        brain_region="Basal ganglia",
        business_function="HR & Organization"
    ),
    System5Term(
        number=9,
        name="Memory Quantization Network",
        bracket_notation="((()()))()",
        description="Network of quantized memory for structured storage and retrieval",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Hippocampus",
        business_function="Knowledge Management"
    ),
    System5Term(
        number=10,
        name="Emotional Equilibrium Mechanism",
        bracket_notation="((())())()",
        description="Mechanism balancing various emotional states for psychological stability",
        polarity=Polarity.PARTICULAR,
        triad=Triad.AUTONOMIC,
        brain_region="Amygdala",
        business_function="Employee Wellbeing"
    ),
    System5Term(
        number=11,
        name="Universal Discretion Matrix",
        bracket_notation="(((())()))",
        description="Matrix of universal discretion underlying individual decision-making",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Prefrontal cortex",
        business_function="Governance"
    ),
    System5Term(
        number=12,
        name="Social Perception Marketplace",
        bracket_notation="(()()()())",
        description="Social environment as marketplace of perception",
        polarity=Polarity.PARTICULAR,
        triad=Triad.SOMATIC,
        brain_region="Social cognition areas",
        business_function="Sales"
    ),
    System5Term(
        number=13,
        name="Intuitive Vision Synthesis",
        bracket_notation="((())()())",
        description="Synthesis combining intuitive insights with conscious ideas",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Right hemisphere",
        business_function="Development"
    ),
    System5Term(
        number=14,
        name="Right Hemisphere Insight Connectivity",
        bracket_notation="((()))(())",
        description="Connectivity of insights associated with right hemisphere",
        polarity=Polarity.PARTICULAR,
        triad=Triad.CEREBRAL,
        brain_region="Right hemisphere",
        business_function="Creative Direction"
    ),
    System5Term(
        number=15,
        name="Social Technique Organization",
        bracket_notation="((()())())",
        description="Organization of social interactions and techniques",
        polarity=Polarity.PARTICULAR,
        triad=Triad.SOMATIC,
        brain_region="Social cognition",
        business_function="HR & IT"
    ),
    System5Term(
        number=16,
        name="Language-Driven Behavioral Formulation",
        bracket_notation="(((()))())",
        description="Formulation of behavior driven by language",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Broca's area",
        business_function="Production"
    ),
    System5Term(
        number=17,
        name="Left Hemisphere Technique Application",
        bracket_notation="((()()()))",
        description="Application of techniques associated with left hemisphere",
        polarity=Polarity.PARTICULAR,
        triad=Triad.CEREBRAL,
        brain_region="Left hemisphere",
        business_function="Technical Operations"
    ),
    System5Term(
        number=18,
        name="Integrated Memory Resource System",
        bracket_notation="(((()())))",
        description="System integrating memory resources for efficient retrieval",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.CEREBRAL,
        brain_region="Memory systems",
        business_function="Finance/Treasury"
    ),
    System5Term(
        number=19,
        name="Balanced Response Coordination",
        bracket_notation="(((())))())",
        description="Coordination of balanced responses proportionate to stimuli",
        polarity=Polarity.PARTICULAR,
        triad=Triad.SOMATIC,
        brain_region="Cerebellum",
        business_function="Quality Assurance"
    ),
    System5Term(
        number=20,
        name="Proprioceptive Sensory Field",
        bracket_notation="()()()()()",
        description="Field of sensory perception for body position awareness",
        polarity=Polarity.UNIVERSAL,
        triad=Triad.SOMATIC,
        brain_region="Proprioceptive system",
        business_function="Market Sensing"
    ),
]


# =============================================================================
# MAPPING FUNCTIONS
# =============================================================================

def normalize_bracket(bracket: str) -> str:
    """Normalize bracket notation by removing spaces and extra characters."""
    return bracket.replace(" ", "").replace(")", ")").replace("(", "(")


def bracket_to_canonical(bracket: str) -> str:
    """
    Convert Dan's bracket notation to our canonical forest notation.
    
    Dan's notation uses nested parentheses for a single rooted tree.
    Our notation uses the same but represents forests (multiple trees).
    """
    # Remove any trailing characters and normalize
    bracket = normalize_bracket(bracket)
    
    # The bracket notation should already be in canonical form
    # Just ensure it's properly formatted
    return bracket


def find_matching_forest(bracket: str, forests: List[RootedForest]) -> Optional[RootedForest]:
    """Find the forest that matches the given bracket notation."""
    target = normalize_bracket(bracket)
    
    for forest in forests:
        if forest.canonical() == target:
            return forest
    
    return None


def create_term_forest_mapping() -> Dict[int, Tuple[System5Term, Optional[RootedForest]]]:
    """
    Create a mapping between System 5 terms and rooted forests.
    
    Returns a dictionary mapping term number to (term, forest) tuple.
    """
    forests = list(get_system5_configurations())
    mapping = {}
    
    for term in SYSTEM5_TERMS:
        forest = find_matching_forest(term.bracket_notation, forests)
        mapping[term.number] = (term, forest)
    
    return mapping


# =============================================================================
# VIRTUAL IMAGE ANALYSIS
# =============================================================================

def identify_virtual_image_terms() -> List[System5Term]:
    """
    Identify the terms that correspond to virtual image configurations.
    
    Based on our analysis, virtual image configurations have exactly 3 trees.
    """
    forests = list(get_system5_configurations())
    virtual_image_terms = []
    
    for term in SYSTEM5_TERMS:
        forest = find_matching_forest(term.bracket_notation, forests)
        if forest and forest.tree_count() == 3:
            virtual_image_terms.append(term)
    
    return virtual_image_terms


def get_triadic_organization() -> Dict[Triad, List[System5Term]]:
    """Get terms organized by their triad association."""
    organization = {triad: [] for triad in Triad}
    
    for term in SYSTEM5_TERMS:
        if term.triad:
            organization[term.triad].append(term)
    
    return organization


# =============================================================================
# SCHWARZ CYCLE INTEGRATION
# =============================================================================

@dataclass
class SchwarzBranch:
    """A branch in the Schwarz trifurcation."""
    name: str
    description: str
    value_system: str
    outcome: str


SCHWARZ_TRIFURCATION = [
    SchwarzBranch(
        name="A: More of the Same",
        description="Continuation of present materialistic-dualist paradigm",
        value_system="ER (StriveDrive)",
        outcome="Narrow rationalism, technocratic imperialism, economism"
    ),
    SchwarzBranch(
        name="B: Destructuration",
        description="Return to lower systems of value",
        value_system="DQ, CP, BO",
        outcome="Nationalism, ethnocentrism, tribalism"
    ),
    SchwarzBranch(
        name="C: Metamorphosis",
        description="Transition to humanistic and integrative systems",
        value_system="FS, GT",
        outcome="Cooperation, equity, conscious integration"
    ),
]


def map_trifurcation_to_virtual_images() -> Dict[str, List[System5Term]]:
    """
    Map the Schwarz trifurcation branches to virtual image configurations.
    
    The three branches (A, B, C) correspond to the three virtual image
    configurations, representing different evolutionary pathways.
    """
    virtual_terms = identify_virtual_image_terms()
    
    # Map based on structural properties
    # This is a conceptual mapping based on the analysis
    mapping = {
        "A": [],  # Continuation - hierarchical structure
        "B": [],  # Regression - flat structure
        "C": [],  # Metamorphosis - balanced structure
    }
    
    for term in virtual_terms:
        forest = find_matching_forest(
            term.bracket_notation, 
            list(get_system5_configurations())
        )
        if forest:
            analysis = analyze_forest(forest)
            # Classify based on structure
            if analysis.max_depth >= 2:
                mapping["A"].append(term)
            elif analysis.tree_sizes == [2, 2, 1]:
                mapping["C"].append(term)
            else:
                mapping["B"].append(term)
    
    return mapping


# =============================================================================
# REPORTING
# =============================================================================

def print_term_mapping_report():
    """Print a comprehensive report of term-to-forest mappings."""
    print("=" * 80)
    print("SYSTEM 5 TERM-TO-FOREST MAPPING REPORT")
    print("=" * 80)
    
    mapping = create_term_forest_mapping()
    
    matched = 0
    unmatched = 0
    
    for num, (term, forest) in sorted(mapping.items()):
        print(f"\nT{num:02d}: {term.name}")
        print(f"     Bracket: {term.bracket_notation}")
        print(f"     Polarity: {term.polarity.value}")
        print(f"     Triad: {term.triad.value if term.triad else 'N/A'}")
        
        if forest:
            analysis = analyze_forest(forest)
            print(f"     Forest: {analysis.bracket_notation}")
            print(f"     Trees: {analysis.tree_count}, Sizes: {analysis.tree_sizes}, Depth: {analysis.max_depth}")
            matched += 1
        else:
            print(f"     Forest: NOT FOUND")
            unmatched += 1
    
    print("\n" + "=" * 80)
    print(f"SUMMARY: {matched} matched, {unmatched} unmatched")
    print("=" * 80)
    
    # Virtual image analysis
    print("\nVIRTUAL IMAGE TERMS:")
    print("-" * 40)
    for term in identify_virtual_image_terms():
        print(f"  T{term.number:02d}: {term.name}")
    
    # Triadic organization
    print("\nTRIADIC ORGANIZATION:")
    print("-" * 40)
    for triad, terms in get_triadic_organization().items():
        print(f"\n{triad.value}:")
        for term in terms:
            print(f"  T{term.number:02d}: {term.name}")


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    print_term_mapping_report()
